<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.qtpselenium.rediff.hybrid.testcases.stocksuite.BuySellStockTest" tests="2" time="226.522" ignored="0" failures="0" timestamp="11 Apr 2018 10:36:17 GMT" skipped="0" hostname="DESKTOP-NM05SVP" errors="1">
  <testcase name="buyOrSellStockTest" time="145.423" classname="com.qtpselenium.rediff.hybrid.testcases.stocksuite.BuySellStockTest"/>
  <testcase name="checkTransactionHistoryTest" time="81.099" classname="com.qtpselenium.rediff.hybrid.testcases.stocksuite.BuySellStockTest">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.qtpselenium.rediff.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
	at com.qtpselenium.rediff.hybrid.testcases.stocksuite.BuySellStockTest.checkTransactionHistoryTest(BuySellStockTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
	Actual average is 0.00Expected was 38.775510204081634
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.qtpselenium.rediff.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:348)
	at com.qtpselenium.rediff.hybrid.keywords.AppKeywords.checkHistory(AppKeywords.java:162)
	... 26 more
]]>
    </error>
  </testcase> <!-- checkTransactionHistoryTest -->
</testsuite> <!-- com.qtpselenium.rediff.hybrid.testcases.stocksuite.BuySellStockTest -->
