<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NM05SVP" ignored="0" name="Add Delete Stock Test" tests="2" failures="1" timestamp="11 Apr 2018 10:36:17 GMT" time="266.596" errors="0">
  <testcase name="addStockTest" time="152.025" classname="com.qtpselenium.rediff.hybrid.testcases.stocksuite.AddDelStockTest"/>
  <testcase name="deleteStockTest" time="112.545" classname="com.qtpselenium.rediff.hybrid.testcases.stocksuite.AddDelStockTest">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at com.qtpselenium.rediff.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
	at com.qtpselenium.rediff.hybrid.testcases.stocksuite.AddDelStockTest.deleteStockTest(AddDelStockTest.java:37)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
	Stock found after deletion Tata Steel Ltd.
	at com.qtpselenium.rediff.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:348)
	at com.qtpselenium.rediff.hybrid.keywords.AppKeywords.deleteStock(AppKeywords.java:111)
	... 26 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- deleteStockTest -->
</testsuite> <!-- Add Delete Stock Test -->
